### ISSUE TITLE
Stake module TODO

### ISSUE THREAD

**Issue by shanev** [rocket-protocol/stakebird#12]
- [ ] check if expected events are fired in abci functions
- [ ] add Msgs to proto
- [ ] update README
- [ ] issue with exported validator type

**Comment by shanev** [comment]
Created separate issues.
